Add formatting, fix some bugs

diff --git a/chat b/chat
--- a/chat
+++ b/chat
@@ -21,8 +21,14 @@ mkdir -p "$conversations_dir"
 # ------------------------------------------------------------------------------
 # Check for required tools and environment variables
 # ------------------------------------------------------------------------------
+if ! command tput -V &> /dev/null; then
+  echo >&2 "Error: tput is not installed or is not on your PATH"
+  exit 1
+fi
+
 if ! command gpt --help &> /dev/null; then
   echo >&2 "Error: gpt is not installed or is not on your PATH"
+  echo >&2 "See https://github.com/sysread/bash-gpt for installation instructions"
   exit 1
 fi
 
@@ -145,7 +151,7 @@ repeat_conversation() {
     esac
 
     echo -e "$prefix"
-    echo -e "$msg"
+    gum format "$msg"
     echo
   done
 }
@@ -164,7 +170,7 @@ select_conversation() {
   local choice
   local file
 
-  choice=$(list_conversations | gum filter --fuzzy --sort || true)
+  choice=$(list_conversations | gum filter --sort || true)
 
   if [ -n "$choice" ]; then
     file=$(find "$conversations_dir" -name "*.txt" -exec grep -l "^Title: $choice" {} \;)
@@ -206,11 +212,40 @@ copy_file_to_clipboard() {
   esac
 }
 
+wrap() {
+  local buffer=""
+  local lines=0
+  local maxcols
+
+  maxcols=$(tput cols)
+
+  IFS=""
+  while read -r -N1 char; do
+    cols=${#buffer}
+
+    if [[ "$char" == $'\n' ]]; then
+      buffer=""
+      lines=$((lines + 1))
+      printf '\n'
+    elif ((cols < maxcols)); then
+      buffer+="$char"
+      printf '%s' "$char"
+    else
+      buffer="$char"
+      lines=$((lines + 1))
+      printf '\n'
+      printf '%s' "$char"
+    fi
+  done
+}
+
 converse() {
-  local placeholder="ctrl-d submits; esc cancels; send \\f to copy a file to clipboard"
+  local placeholder="ctrl-d submits | esc cancels | send \\f to copy a file to clipboard"
+  local lines
+  local i
 
   while true; do
-    msg=$(gum write --width 100 --height 10 --char-limit 0 --placeholder "$placeholder" || true)
+    msg=$(gum write --width 100 --height 20 --char-limit 0 --placeholder "$placeholder" || true)
 
     case "$msg" in
       '')
@@ -225,15 +260,23 @@ converse() {
         conversation+=(-u "$msg")
 
         echo -e "${green}You:${reset}"
-        echo "$msg"
-        echo
+        gum format "$msg"
 
         echo -e "${green}GPT:${reset}"
-        gpt --no-cache "${conversation[@]}" | tee "$tmp"
+
+        # Initially display gpt's output as it arrives
+        gpt --no-cache "${conversation[@]}" | wrap | tee "$tmp"
+
+        # Then clear the output and replace it with formatted output
+        lines=$(wc -l < "$tmp" | awk '{ print $1 }')
+        for ((i = 0; i < lines; i++)); do
+          tput cuu1 && tput el
+        done
+
+        gum format < "$tmp"
 
         conversation+=(-s "$(cat "$tmp")")
-
-        save_conversation
+        save_conversation &
         ;;
     esac
   done
@@ -255,6 +298,7 @@ choices=(
 while true; do
   case "$(gum choose --ordered "${choices[@]}")" in
     "$new_conversation")
+      title="New conversation"
       print_conversation_title
       converse
       ;;
