formatting fixup

diff --git a/gpt b/gpt
--- a/gpt
+++ b/gpt
@@ -5,12 +5,12 @@ set -eu -o pipefail
 # ------------------------------------------------------------------------------
 # Check for required tools and environment variables
 # ------------------------------------------------------------------------------
-if ! command -v curl &>/dev/null; then
+if ! command -v curl &> /dev/null; then
   echo >&2 "Error: curl is not installed."
   exit 1
 fi
 
-if ! command -v jq &>/dev/null; then
+if ! command -v jq &> /dev/null; then
   echo >&2 "Error: jq is not installed."
   exit 1
 fi
@@ -39,7 +39,7 @@ RESET="\033[0m"
 function usage() {
   local exit_code="${1:-0}"
 
-  cat <<EOL
+  cat << EOL
 usage: gpt [OPTIONS]
 
 Options:
@@ -85,13 +85,13 @@ build_payload() {
     val="${val#"${val%%[![:space:]]*}"}"
     val="${val%"${val##*[![:space:]]}"}"
 
-    payload=$(jq --arg k "$key" --arg v "$val" '. + {($k): $v}' <<<"$payload")
+    payload=$(jq --arg k "$key" --arg v "$val" '. + {($k): $v}' <<< "$payload")
   done
 
   # Loop through all_prompts to add more messages
   for prompt in "${PROMPTS[@]}"; do
     new_message=$(jq -n --arg content "$prompt" '{"role": "user", "content": $content}')
-    payload=$(jq --argjson new_msg "$new_message" '.messages += [$new_msg]' <<<"$payload")
+    payload=$(jq --argjson new_msg "$new_message" '.messages += [$new_msg]' <<< "$payload")
   done
 
   echo "$payload"
@@ -114,9 +114,9 @@ get_completion() {
     -N "https://api.openai.com/v1/chat/completions" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $OPENAI_API_KEY" \
-    -d "$(build_payload)" |
-    inspect |
-    while IFS= read -r line; do
+    -d "$(build_payload)" \
+    | inspect \
+    | while IFS= read -r line; do
       if [[ $line == *"[DONE]"* ]]; then
         exit 0
       fi
@@ -124,7 +124,7 @@ get_completion() {
       processed_line=$(echo "$line" | awk '/data: / { sub(/^data: /, ""); print }')
 
       if [[ -n $processed_line ]]; then
-        if echo "$processed_line" | jq -e 'has("error")' >/dev/null 2>&1; then
+        if echo "$processed_line" | jq -e 'has("error")' > /dev/null 2>&1; then
           error_message=$(echo "$processed_line" | jq -r '.error.message')
           echo -e "\e[31m${error_message}\e[0m" # Print in red
           exit 1
@@ -184,7 +184,7 @@ cache_key=$(cache_key)
 cache_file="$cache_dir/$cache_key"
 
 # Ensure the cached results directory exists
-mkdir -p "$cache_dir" 2>/dev/null || true
+mkdir -p "$cache_dir" 2> /dev/null || true
 
 # Clear all cached results if --clear-all was set
 if [ "$CLEAR_CACHE_ALL" = "true" ]; then
@@ -198,7 +198,7 @@ fi
 
 if [ "$NO_CACHE" = "true" ]; then
   get_completion
-elif [ -e "$cache_file" ]; then
+elif [ -e "$cache_file" ] && [ -s "$cache_file" ]; then
   cat "$cache_file"
 else
   get_completion | tee "$cache_file"
